apiVersion: 1.1
image:
  imageType: iso 
  arch: x86_64
  baseImage: SL-Micro.x86_64-6.0-Base-SelfInstall-GM2.install.iso
  outputImageName: rancher-3node-x86_64-6.0.iso
operatingSystem:
  isoConfiguration:
    installDevice: /dev/mmcblk0
  kernelArgs:
  - nomodeset
  users:
  - username: root
    encryptedPassword: "$6$DIL3SYTayoaM13GP$zAfXEofZd154Wuuj.fMqJXKd2p8fieu75zLgta6dWz7rCHsxw0x4CcFjLH3V5Dy4sQKN9/VotNS9E37RYRTeD."
  - username: FC2505001
    encryptedPassword: "$6$GjhSkXlaRH9c7FEw$FESxztveMbTXHh2ZKvIUy1jezzd2w4xs915pg0uU3pKtIEAog0mryE1cdMQ5dLLAi70emdy2wKIy11dN4ZAfG1" 
kubernetes:
  version: v1.31.4+k3s1 #v1.31.3+rke2r1
  network:
    apiHost: 10.203.203.75.sslip.io
    apiVIP: 10.203.203.75
  nodes:
    - hostname: FC2505001.cipos.com
      type: server
      initializer: true
    - hostname: node2.suse.com
      type: agent
    - hostname: node3.suse.com
      type: agent
  helm:
    charts:
      - name: cert-manager
        version: 1.14.2
        repositoryName: jetstack
        targetNamespace: cert-manager
        createNamespace: true
        installationNamespace: kube-system
        valuesFile: certmanager.yaml
      - name: rancher
        version: 2.10.1
        repositoryName: rancher-prime
        targetNamespace: cattle-system
        createNamespace: true
        installationNamespace: kube-system
        valuesFile: rancher.yaml
    repositories:
      - name: jetstack
        url: https://charts.jetstack.io
      - name: rancher-prime
        url: https://charts.rancher.com/server-charts/prime
